services:
  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - mongo_data:/data/db

  phonebook-api:
    image: phonebook-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      MongoDbSettings__ConnectionString: mongodb://${ADMIN_USERNAME}:${ADMIN_PASSWORD}@mongo:${MONGO_PORT}
      MongoDbSettings__DatabaseName: ${MONGO_DB_NAME}
      Jwt__SecretKey: ${Jwt__SecretKey}
      Jwt__Issuer: ${Jwt__Issuer}
      Jwt__Audience: ${Jwt__Audience}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - mongo

volumes:
  mongo_data:
